force-app/main/default/objects/Lead_Rating__mdt.object
<CustomObject>
    <description>Store Lead Ratings Based on Company Name</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Stores Company Name</description>
        <label>Company Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Stores Lead Rating</description>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                    <default>true</default>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Cold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Rating</label>
    <pluralLabel>Lead Ratings</pluralLabel>
</CustomObject>

force-app/main/default/classes/LeadRatingMapUtil.cls
public with sharing class LeadRatingMapUtil {
    private Set<String> companyNames;
    private List<Lead_Rating__mdt> allMappings;
    public static LeadRatingMapUtil leadRatingMapObj;

    public static LeadRatingMapUtil getLeadRatingMap(Set<String> companyNames){
        if(leadRatingMapObj == null){
            leadRatingMapObj = new LeadRatingMapUtil(companyNames);
        }
        return leadRatingMapObj;
    }

    private LeadRatingMapUtil(Set<String> companyNames){
        this.companyNames = companyNames;
        fetchMapping();
    }

    private void fetchMapping(){
        allMappings = [Select Id, Company_Name__c, Rating__c from Lead_Rating__mdt where Company_Name__c in: companyNames];
    }

    public String getMapping(String companyName){
        String retVal;
        for(Lead_Rating__mdt single: allMappings){
            if(single.Company_Name__c.equalsIgnoreCase(companyName)){
                retVal = single.Rating__c;
                break;
            }
        }
        return retVal;
    }


}